### ISSUE TITLE
Tests for JWT extractor

### ISSUE THREAD

**Issue by AaronErhardt** [Trioxidation/Triox#10]
Tests for the extractor in `jwt.rs` which extracts the [JWT](https://jwt.io/) as String from the request headers. There should be multiple tests for the `from_request` method of the `JWT` struct whether it can properly extract the JWT and whether it can detect error cases correctly. The [api documentation](https://github.com/AaronErhardt/Triox/blob/master/API.md) describes how a correct request with an authorization or cookie header should look like. The extraction of the claims itself can be assumed to be correct because they are done by the [jsonwebtoken crate](https://docs.rs/jsonwebtoken/7.2.0/jsonwebtoken/index.html).

List of possible test scenarios:
- [ ] Correct authorization using authorization header
- [ ] Correct authorization using cookie header
- [ ] Authorization using both headers (authorization should be preferred)
- [ ] Invalid authorization header (no bearer authorization)
- [ ] Empty cookie value
- [ ] JWT is an invalid String
- [ ] JWT exceeds size limit (to prevent DOS)

**Comment by realaravinth** [comment]
closing because we no longer use jwt
