### ISSUE TITLE
[Community] Matrix or Discord for the project?

### ISSUE THREAD

**Issue by realaravinth** [Trioxidation/Triox#16]
Github issues send out emails every time there's activity so what do you think about creating a Matrix room or a Discord equivalent for regular discussions? 

For instance, I'm working on setting up CI workflows for running tests and code coverage over at [my fork](https://github.com/realaravinth/Triox) of this project and there are a bunch of things that I wish to discuss with you/other devs. 

Personally, I prefer Matrix but this your project :)

**Comment by AaronErhardt** [comment]
Thanks for your suggestion. I prefer Matrix as well. Actually, Triox could support Matrix at some point.... but I guess for now a regular Matrix server will do the job ;)

**Comment by realaravinth** [comment]
I created a community on Matrix. I have to say, Matrix is a bit weird :laughing: 

https://matrix.to/#/+triox:matrix.org
