### ISSUE TITLE
Demo server is broken/hijacked

### ISSUE THREAD

**Issue by SeriousBug** [Trioxidation/Triox#41]
Hey, looks like the demo server is either entirely broken, or has been hijacked to redirect to another website.

![Screenshot_20220213_162400](https://user-images.githubusercontent.com/1008124/153775660-2c780706-051a-4b31-963f-b414e9bede47.png)

**Comment by AaronErhardt** [comment]
Thanks for pointing this out!

Seems like the DNS record just points to a random website. The demo server has been offline for quite some time now. Anyway, I've updated the README to remove the link and to better represent the current status.
